### ISSUE TITLE
Request: Styling and functionality of PS

### ISSUE THREAD

**Issue by sarrene** [angek/ProjectSpoon#21]
Good morning, 
I have a request if I may. I know several developers that i work with that would love to get PS. I have done a lot of custom work for some of our clients in the past with PF and then PK. 

I have a few requests if I may, some are my own, but most come from the clients that I work with for their projects. This one will be more about styling and front end functionality. 

The reason is because my own company (software development/platform as a service) and many of our clients (game and 3d simulation application developers) wish we had something more like the backend for the front end. I end up helping our clients on the side to get their PF/PK to look and function more like the back end (admin). 

1) More compact styling that allows you the option to inherit the templates base css and styling or select PS's styling, but not quite as .. bubbly. _(I am willing to help anywhere I am able when I am able)_
- Example: Spacing between tasks is quite large by default, on a lot of templates from more common sites, this spacing becomes huge. It takes up a lot of space

2) Options for more up front information to be displayed (without a drop down for each. Project/Milestone/Task summery (perhaps with option to select number of characters to display using Joomla's inherent "read more" functionality (ive done this several times for clients)

3) Different styling of the Task progress. More of a slider with an optional display of the % instead of the bubble. 

4) Option to select permissions based on Project, Milestones and (most importantly) tasks. Our company would love to display the Gantt and current projects/milestones but not allow the general public to see the tasks themselves. 

Okay, I think I am done now. Thank you so very much for taking the time to read. I appreciate it a LOT. I am quite excited about this, and will allow me to plan out my time a bit more so perhaps I can get some sleep eventually. 

Regards,
Sarrene'

**Comment by angek** [comment]
I know this topic is quite old but just for the record, styling of ProjectSpoon frontend displays is very much a personal thing. Joomla provides the ability to create overrides for this and it's really up to the end user to implement these as they see fit. Having said that, I do offer paid customisation services :)
