### ISSUE TITLE
EasySocial y K2 Plugins

### ISSUE THREAD

**Issue by AyelGoth** [angek/ProjectSpoon#36]
Simplemente propongo crear dos plugins, uno para crear un enlace de autor al perfil y al avatar del componente K2. La otra propuesta es crear un plugins para enlazar al perfil de EasySocial y a la foto de avatar del mismo componente.

**Comment by angek** [comment]
there currently exists a system plugin for Projectspoon that allows you to pick the User Profile Link type.
![user_profile_link](https://user-images.githubusercontent.com/1072484/43053827-11b86766-8e72-11e8-82bc-992c20d748ec.png)
