### ISSUE TITLE
bug on task assignee

### ISSUE THREAD

**Issue by enbzz** [angek/ProjectSpoon#42]
when creating a new task on the frontend, after saving and "create new", from the second task onward the list of users is no longer accessed and it is not possible to assign a new assignee to the task. It is necessary to "save and close" and re-edit the task to have the user list accessible again.

**Comment by angek** [comment]
this bug is being caused because  ajaxChosen for assignees is not passing project id correctly in the ajax url. Further investigation has revealed that it also affects predecessor selection.

**Comment by angek** [comment]
closing this and creating new issue ( issue #45 ) for correct reference.
