### ISSUE TITLE
Issue in assignees

### ISSUE THREAD

**Issue by rkoho** [angek/ProjectSpoon#47]
Hi, got the following error message related to assignees: 

0 Too few arguments to function PKApplicationHelper::formatMonetary(), 1 passed in /home/hhxxxxx/public_html/administrator/components/com_pkusers/views/assignees/tmpl/default.php on line 227 and at least 2 expected

It appears in backend when clicking the assignees menu item and in frontend when clicking the assigned persons profile picture (details).

How to fix it?

**Comment by angek** [comment]
hey @rkoho will take a look at this shortly and get back to you.

**Comment by rkoho** [comment]
hey @angek and thank you for your quick reply to this. However, I had those currency options made before this issue. It occurred when I added an assignee and saved it. At the moment I don't have access to assignees (via the menu item) in back end at all, I get the error message immediately.
Any suggestions?

**Comment by angek** [comment]
@rkoho,

OK now I understand.

do me a favour and locate the following file:

`/libraries/projectspoon/application/helper.php`

locate the formatMonetary function at around line 467 and replace the following line:

`public static function formatMonetary($value, $currency_options, $pid = null)`

with this one:

`public static function formatMonetary($value, $currency_options = null, $pid = null)`

let me know if that resolves your issue.

**Comment by rkoho** [comment]
Thank you @angek . This change resolved the issue:)
