### ISSUE TITLE
Some titles not viewing correctly

### ISSUE THREAD

**Issue by rkoho** [angek/ProjectSpoon#48]
Hi, having a minor issue with menu item titles viewing in frontend. The translated value is not visible but the constant is; e.g COM_PKPROJECTS_ADD_TASK is now the visible text, not 'Add Task' as it should be. This occurs only with some menu items, not all. Also strange thing is that with my Finnish translations (fi-FI) all menu items are viewing correctly, Haven't touched the en-GB files, either could see any issues in en-GB language files. 

I think I had this same issue with Projectknife when I had it earlier installed. Suggestions, how to fix this? 

![projectspoon-dashboard](https://user-images.githubusercontent.com/36237474/46679704-36fdea80-cbf0-11e8-9d55-4790b355762a.png)

**Comment by angek** [comment]
Hey @rkoho is this issue limited to the constants in the screenshot you provided or are there more?

**Comment by angek** [comment]
@rkoho try the following:

open the file:

`administrator/language/en-GB/en-GB.com_pkdashboard.ini`

and add the following to the bottom of the file:

```
COM_PKPROJECTS_ADD_PROJECT = "Add Project"
COM_PKMILESTONES_ADD_MILESTONE = "Add Milestone"
COM_PKTASKS_ADD_TASK = "Add Task"
COM_PKTIME_DASHBOARD_ADD_TIME = "Add Time Record"
```


does that solve you're issue?

**Comment by rkoho** [comment]
Hey @angek ; to your question: Issue is not limited only to that view (screenshot). As far as I can see there are two other views  where I found similar issues: 
- In Projects view constant COM_PKMILESTONES_SUBMENU_MILESTONES is visible
- and in milestones view: COM_PKTASKS_SUBMENU_TASKS

I made the changes as you adviced and it resolved the issue, great, thank you! To which files I should make changes in order to fix those two lines above?

**Comment by angek** [comment]
try adding:

`COM_PKMILESTONES_SUBMENU_MILESTONES = "Milestones"`

to

`administrator/language/en-GB/en-GB.com_pkprojects.ini`

and

`COM_PKTASKS_SUBMENU_TASKS = "Tasks"`

to 

`administrator/language/en-GB/en-GB.com_pkmilestones.ini`

**Comment by rkoho** [comment]
Issue resolved, thank you! I also noticed later that COM_PKTASKS_SUBMENU_TASKS ("Tasks") was missing also in projects view. I added it to en-GB.com.pkprojects.ini  and it resoved that. 
Thank you again for your immediate responses. And F.Y.I I have good Finnish translations in case you are interested to have them. (but have to review them first since the changes from Projectknife days)
