### ISSUE TITLE
Milestone View Options

### ISSUE THREAD

**Issue by angek** [angek/ProjectSpoon#9]
Introduce configurable options in global config (show project, show author, show tags, show start date, show end date etc) for a milestone's detail view.

**Comment by micker** [comment]
Cool good idea

**Comment by angek** [comment]
implemented with commit 2734e65
![projectspoon_milestones_config](https://user-images.githubusercontent.com/1072484/36136911-c3f98ae0-10e6-11e8-80e5-569ea6607680.png)
